DROP DATABASE IF EXISTS algorithm;
create database algorithm;
use algorithm;
CREATE TABLE `product` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` varchar(45) NOT NULL DEFAULT '',
  `tag_source` text NOT NULL,
  `tags_id` varchar(1000) NOT NULL DEFAULT '',
  `update_time` varchar(45) DEFAULT '',
  `category` int(10) unsigned DEFAULT '0',
  `sub_category` int(10) unsigned DEFAULT '0',
  `brand` int(10) unsigned NOT NULL DEFAULT '0',
  `detail_images` varchar(4000) NOT NULL DEFAULT '',
  `thumb_images` varchar(500) DEFAULT '',
  `suitable_images` varchar(500) NOT NULL DEFAULT '',
  `white_suitable` varchar(500) NOT NULL DEFAULT '',
  `tag_status` smallint(5) unsigned DEFAULT NULL,
  `visenze_result` text,
  `merchant` int(10) unsigned NOT NULL DEFAULT '0',
  `koutu` varchar(500) DEFAULT '',
  `shop_url` varchar(500) NOT NULL DEFAULT '',
  `merchant_en` varchar(45) DEFAULT NULL,
  `brand_en` varchar(45) DEFAULT NULL,
  `price` int(11) unsigned DEFAULT NULL,
  `discount_price` int(11) unsigned DEFAULT NULL,
  `discount_percent` int(7) unsigned DEFAULT NULL,
  `buy_size` varchar(500) NOT NULL DEFAULT '[]',
  `buy_color` varchar(500) NOT NULL DEFAULT '[]',
  `stock_info` varchar(1000) NOT NULL DEFAULT '{}',
  `buy_size_type` varchar(100) DEFAULT NULL,
  `status` int(10) unsigned NOT NULL DEFAULT '1',
  `tags_id_en` varchar(5000) NOT NULL DEFAULT '',
  `have_main` bit(1) NOT NULL DEFAULT b'0',
  `have_sub` bit(1) NOT NULL DEFAULT b'0',
  `have_color` bit(1) NOT NULL DEFAULT b'0',
  `have_cutting` bit(1) NOT NULL DEFAULT b'0',
  `have_pattern` bit(1) NOT NULL DEFAULT b'0',
  `group_id` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `pid_unique` (`pid`)
) ENGINE=InnoDB AUTO_INCREMENT=22637 DEFAULT CHARSET=utf8 ;
